### ISSUE TITLE
support plugins with docsify init

### ISSUE THREAD

**Issue by tool3** [docsifyjs/docsify-cli#98]
Hi!

I have been using `docsify` for some of my projects, and I absolutely love it. even made a github-action out of it for the github action hackathon ;)

I think support for being able to `init` a `docs` directory with a list of plugins, maybe loaded from a predefined file or even through cli flags, would be so great, and it will better support `docsify` in CI/CD.

**Comment by anikethsaha** [comment]
You meant something like this ?

`docsify init -p plugin1, plugin2`

by `plugin1` and `plugin2` I meant relative path to these  as this will simply get copied to the template generated ....
something like this !

**Comment by tool3** [comment]
yeah exactly! so if I do:
```bash
docsify init docs/ -p docsify-themeable docsify-tabs docsify
```
it would create those `<script>` tags in `index.html` with those plugins from cdn\local.

I guess options for plugins would mean restricting it to file based only (something like `docsify init docs/ -p plugins.json`), but that's an implementation  decision 😄

**Comment by anikethsaha** [comment]
We cant support a config file for the CLI at this point as it would create an confusion for users as the html too has a config object. 

Though we can consider this `docsify init docs/ -p docsify-themeable docsify-tabs docsify`

### PoC is Welcome for this

**Comment by tool3** [comment]
sure I'll have a go

**Comment by jhildenbiddle** [comment]
Please ensure that docsify plugin versions are locked to the current major version to align with the work done here: https://github.com/docsifyjs/docsify-cli/pull/107

To be clear, we don't know the major version of third-party plugins so we can't lock those. I am only referring to plugins within the docsify repo.

**Comment by anikethsaha** [comment]
@jhildenbiddle I didnt get this ? 

Did you mean any compatibility issue?

**Comment by jhildenbiddle** [comment]
I mean the following plugins:

https://cdn.jsdelivr.net/npm/docsify@4/lib/plugins/

... are all maintained by the docsify team, stored in the same repo as docsify, and therefore designed to work with a specific version of docsify. If we add the ability to specify plugins using the CLI as mentioned above:

```shell
docsify init docs/ -p external-script search
```

We need to lock the plugins loaded to the same major version of docsify:

```html
<script src="//cdn.jsdelivr.net/npm/docsify@4/lib/plugins/external-script.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/docsify@4/lib/plugins/search.min.js"></script>
```

Also, I don't think we should tackle loading third-party plugins initially. That gets complicated quickly. For example:

1. How do we handle plugin URL changes?
1. How do we know if an plugin is compatible with the latest version of docsify?
1. How do we know the full list of resources that need to be loaded with a plugin? For example, many plugins require loading separate `.js` and `.css` files.
1. How do we know what configuration options need to be added in order for the plugin to work properly?

Since the docsify team controls all of the plugins listed above, we know how to answer these questions. With third-party plugins we don't. We could, but it will require coordination with plugin/theme authors.

**Comment by anikethsaha** [comment]
I see, 
There is an open PR for this #99 

I did request the changes you mentioned. 

👍 


Also, we don't have to think about loading third-party plugins with respect to compatibility issues. 
Though currently, we don't have any breaking changes in plugins integration.

**Comment by jhildenbiddle** [comment]
Ahh. Didn’t realize there was a related PR in place. Thanks, @anikethsaha.

Regarding the third party plugins, I only mentioned those because docsify-themeable and docsify-tabs were used as example in your example cli command:

> Though we can consider this `docsify init docs/ -p docsify-themeable docsify-tabs docsify`

If third-party plugins aren’t supported by the cli, then no worries. If they are (as the example above implies) then there are additional discussions that need to take place.

**Comment by anikethsaha** [comment]
Thats the same I thought , but looking at the PR, it is only implementing only core plugins. 

Though we can include third part as well. 

cc @tool3

**Comment by tool3** [comment]
Hi guys!

To support 3rd party plugins **which have a custom configuration**, obviously this won't work since we don't handle this.

But for 3rd party plugins which have default configurations - this should work 😃
